language: node_js

node_js:
  - "node"

before_script:
  - npm install -g gulp
  
script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "$(git --no-pager show -s --format='%ae' HEAD)"
  - openssl aes-256-cbc -K $encrypted_8b5ed4773e26_key -iv $encrypted_8b5ed4773e26_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - chmod 600 /tmp/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/deploy_key
  - git remote set-url origin git@github.com:UCC-LabCompu2/filminas.git
  - gulp deploy
